baseURL = "http://www.phpspec.net/"
title = "phpspec"
disableHugoGeneratorInject = true

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

[menu]
  [[menu.repo]]
    name = "phpspec repo"
    url = "https://www.github.com/phpspec/phpspec"
  [[menu.repo]]
    name = "prophecy repo"
    url = "https://www.github.com/phpspec/prophecy"

[params]
  version = "v6.1"
  github = "https://www.github.com/phpspec/phpspec"
  githubProphecy = "https://www.github.com/phpspec/prophecy"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageCode = "en"
    languageName = "English"