name: Build

on:
    push:
        branches: [main, next, 9.0]
    pull_request:
    release:
        types: [created]

env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  tools: cs2pr

            - name: Install dependencies
              run: composer install --no-progress

            - name: PHP CS Fixer
              run: vendor/bin/php-cs-fixer fix --dry-run --diff --format=checkstyle | cs2pr

            - name: Psalm
              run: vendor/bin/psalm --version && vendor/bin/psalm

    tests:
        name: Test (PHP ${{ matrix.php }}, ${{ matrix.operating-system }})
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                php: ['8.2', '8.3', '8.4', '8.5']
                operating-system: [ubuntu-latest, macOS-latest, windows-latest]
                composer-flags: ['']
                include:
                    - php: '8.2'
                      operating-system: ubuntu-latest
                      publish-phar: true
                    - php: '8.2'
                      operating-system: ubuntu-latest
                      composer-flags: --prefer-lowest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: sockets
                  coverage: xdebug
                  ini-values: "phar.readonly=0"

            - name: Install dependencies
              run: composer update --no-progress ${{ matrix.composer-flags }}

            - name: Run specs
              run: php bin/phpspec run --format=dot

            - name: Run features
              run: php bin/phpspec run features/
              continue-on-error: ${{ matrix.composer-flags == '--prefer-lowest' || matrix.operating-system == 'windows-latest' }}

            - name: Check coverage
              if: matrix.operating-system == 'ubuntu-latest' && matrix.composer-flags == ''
              run: php -d xdebug.mode=coverage bin/phpspec run --coverage-min=90 -f dot

            - name: Build the PHAR
              if: matrix.publish-phar
              run: |
                  composer global require humbug/box
                  box compile

            - uses: actions/upload-artifact@v4
              name: Publish the PHAR
              if: matrix.publish-phar
              with:
                  name: phpspec.phar
                  path: phpspec.phar

    publish-phar:
        runs-on: ubuntu-latest
        name: Publish the PHAR
        needs: tests
        if: github.event_name == 'release'
        permissions:
            contents: write
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: phpspec.phar
                  path: .
            - name: Upload phpspec.phar
              uses: softprops/action-gh-release@v2
              with:
                  files: phpspec.phar
