name: Docs

on: [push]  # TODO Change back to only master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    name: Build and deploy docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.64.0'
          extended: true
      - name: Build docs
        run: hugo --source docs/ --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs/public